### ISSUE TITLE
Reformat Rescard.jsx

### ISSUE THREAD

**Issue by AarhamH** [jonahkimm/MenuMap#7]
Center Rescard.jsx to be in line with the Sidebar (Sidebar.jsx). You may make any other adjustments to the component if you like within this issue.

Image Evidence:
![image](https://github.com/jonahkimm/MenuMap/assets/105332385/e016e56f-7a89-47f6-b7d0-adf81fefc4a5)

EDIT: It would probably be a good idea to have the restaurant query search Rescard.jsx, just on the top.

**Comment by jonahkimm** [comment]
Sounds good. I will put that into next pull request.
